FROM node:20.19.3
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
COPY web/.next/standalone ./
COPY web/.next/static ./.next/static
COPY web/public ./public
EXPOSE 3000
ENV PORT=3000
CMD ["node", "server.js"]
